# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aaeb84c1d626e7c7b1b983ae8ba72ebb26ccb0401861e9691a2462bf8b1ce8355b6de038258fbba8eb3bdf3adb8a20cf0548471a62328d1de9c575b90a27a7d8

test:
  secret_key_base: 1cda34d7e75a090c74c408512b2c095055b6ec3419dc1805284bdc87225fe7088226fbdb79b38b9dbb8858b8c5d9516b9150e2d646995c31a6e016e9c4b8de60

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
